package com.sid.api.utility;

public interface SQLQueries {

	String FETCH_INFLUENCES_BY_COMPANY_ID = "SELECT bi.id, bi.influence, bi.influence_image FROM app_influences bi  INNER JOIN app_category_influences bci ON bi.id = bci.influence_id  INNER JOIN app_category bc ON bc.id = bci.category_id  INNER JOIN app_company_categories bcc ON bcc.category_id = bc.id  INNER JOIN app_company_details bcd ON bcd.id = bcc.company_id  WHERE bcd.id =  ?;";
	String INSERT_INTO_APP_USER_DETAILS_QUERY = "INSERT INTO app_user_details (id, title, first_name, last_name, email, phone_no, date_of_birth, fb_user_id, gender, country, state, city, zipcode, device_token) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?);";
	String INSERT_INTO_APP_USER_TYPE_QUERY = "INSERT INTO app_user_type (id, type) VALUES(?,?)";
	String INSERT_INTO_APP_SURVEY_ANSWERS_QUERY = "INSERT INTO app_survey_answers (id, rating, description, created_on, user_id, company_id, location) VALUES(?,?,?,?,?,?,?)";
	String INSERT_INTO_APP_SURVEY_ANSWERS_INFLUENCES_QUERY = "INSERT INTO app_survey_answers_influences (id, survey_answers_id, influence_id) VALUES(?,?,?)";
	String INSERT_INTO_APP_COMPANY_DETAILS_QUERY = "INSERT INTO app_company_details (id, name, description, website, email, country, state, city, street, zipcode, fb_link, twitter_link, logo, vicinity, phone_no, additional_phone_no, gender, targeted_gender, age_range) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);";
	String INSERT_INTO_APP_QUESTIONS_QUERY = "INSERT INTO app_questions (id, description) VALUES (?,?)";
	String FETCH_ALL_QUESTIONS_QUERY = "SELECT * FROM app_questions;";
	String DELETE_QUESTION_QUERY = "DELETE FROM app_questions WHERE id = ?";
	String INSERT_INTO_APP_REWARDS_QUERY = "INSERT INTO app_rewards (id, company, reward_description, type, valid_from, valid_till, created_date, reward_packs_id, expired_date, reward_value, no_of_rewards, minimum_reviews, status, icon_url, name, coupon_code, offer_url) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);";
	String INSERT_INTO_REWARD_PACK_QUERY = "INSERT INTO app_reward_packs (id, name, description, level, category, required_reviews_no) VALUES (?,?,?,?,?,?)";
	String VALIDATE_REWARD_PACK_ID_QUERY = "SELECT 1 FROM app_reward_packs WHERE id = ?";
	String DELETE_REWARD_FROM_APP_REWARDS_QUERY = "DELETE FROM app_rewards WHERE id = ?";
	String VALIDATE_REWARD_ID_QUERY = "SELECT 1 FROM app_rewards WHERE id = ?";
	String INSERT_INTO_APP_USER_REWARDS_QUERY = "INSERT INTO app_user_reward (id, user_id, reward_id, is_expired, expiry_date, is_claimed) VALUES(?,?,?,?,?,?)";
	String FETCH_REWARDS_BY_USER_ID_QUERY = "SELECT bur.id AS reward_id, br.company, br.reward_description, br.name, br.type, br.valid_from, br.valid_till, br.created_date, br.reward_packs_id, br.expired_date, br.reward_value, br.status, br.no_of_rewards, br.minimum_reviews, br.icon_url, br.expired_date, br.coupon_code, br.offer_url FROM app_user_reward bur INNER JOIN app_rewards br ON bur.reward_id = br.id WHERE bur.user_id = ? and bur.is_claimed = 'no' and br.no_of_rewards::int > 0 and br.valid_till::date >= now()::date;";
	String CLAIM_REWARD_QUERY = "UPDATE app_user_reward SET is_claimed = ? WHERE id = ?;";
	String FETCH_FUTURE_REWARDS_QUERY = "SELECT br.id as reward_id, br.company, br.reward_description, br.type, br.valid_from, br.valid_till, br.created_date, br.reward_packs_id, br.expired_date, br.reward_value FROM app_rewards br WHERE br.id NOT IN (SELECT reward_id FROM app_user_reward WHERE user_id = ?);";
	String DEACTIVATE_USER_QUERY = "UPDATE app_user_details SET is_active='no' WHERE id = ?;";
	String LOGIN_USER_QUERY = "SELECT is_active FROM app_user_details WHERE id = ?";
	String REMOVE_COMPANY_BY_ID_QUERY = "DELETE FROM app_company_details WHERE id = ?";
	String UPDATE_COMPANY_BY_ID_QUERY = "UPDATE app_company_details SET name = ?, description = ?, website = ?, email = ?, country = ?, state = ?, city = ?, street = ?, zipcode = ?, fb_link = ?, twitter_link = ?, logo = ?, vicinity = ?, phone_no = ?, additional_phone_no = ? WHERE id = ?";
	String INSERT_INTO_INFLUENCES_QUERY = "INSERT INTO app_influences(id, influence, influence_image) VALUES (?,?,?)";
	String DELETE_FROM_INFLUENCES_QUERY = "DELETE FROM app_influences WHERE id = ?";
	String UPDATE_INFLUENCE_QUERY = "UPDATE app_influences SET influence = ?, influence_image = ? WHERE id = ?";
	String UPDATE_QUESTION_QUERY = "UPDATE app_questions SET description = ? WHERE id = ?";
	String INSERT_INTO_APP_APP_FEEDBACK_QUERY = "INSERT INTO app_app_feedback (id, feedback, type, created_date, user_id) VALUES (?,?,?,?,?);";
	String REPORT_ISSUE_QUERY = "INSERT INTO app_issue (id, type, created_date, user_id, description) VALUES (?,?,?,?,?);";
	String SEARCH_REVIEWS_BY_FILTER_QUERY = "SELECT  bsa.rating, bsa.description as review, bi.influences, bsa.company_id, bcd.name, bcd.city, bud.id as user_id, bud.email  FROM app_survey_answers bsa INNER JOIN app_survey_answers_influences bsai ON bsa.id = bsai.survey_answers_id INNER JOIN app_company_details bcd ON bcd.id = bsa.company_id INNER JOIN app_influences bi ON bi.id = bsai.influence_id INNER JOIN app_user_details bud ON bud.id = bsa.user_id  WHERE lower(bcd.name) like lower(?) AND (lower(bcd.city) like lower(?) OR bcd.city is null) AND lower(bsa.rating) like lower(?) AND lower(bsa.description) like lower(?);";
	String FETCH_ALL_USERS_QUERY = "SELECT * from app_user_details";
	String DELETE_ALL_QUESTIONS_QUERY = "DELETE FROM app_questions";
	String TOGGLE_USER_ACCOUNT_STATUS_QUERY = "UPDATE app_user_details SET is_active = Case when is_active='Active' then 'Deactive' ELSE 'Active' END WHERE id = ?;";
	String TOGGLE_OPT_OUT_STATUS_QUERY = "UPDATE app_user_details SET is_opt_out = Case when is_opt_out='Yes' then 'No' ELSE 'Yes' END WHERE id = ?;";
	String FETCH_ALL_APP_FEEDBACK_QUERY = "select bud.first_name, bud.last_name, bud.email, bud.gender, bud.date_of_birth, bud.is_active, bud.zipcode, bud.city, bud.state, bud.country, baf.created_date, baf.feedback from app_user_details bud inner join app_app_feedback baf ON bud.id = baf.user_id;";
	String FETCH_ALL_INFLUENCES_QUERY = "SELECT * FROM app_influences;";
	String FETCH_ALL_COMPANIES_QUERY = "SELECT * FROM app_company_details order by name;";
	String INSERT_INTO_CATEGORY_QUERY = "INSERT INTO app_category (id, category, description) VALUES (?,?,?)";
	String INSTER_INTO_CATEGORY_INFLUENCE_QUERY = "INSERT INTO app_category_influences (id, category_id, influence_id) VALUES (?,?,?)";
	String FETCH_ALL_CATEGORIES_QUERY = "SELECT * FROM app_category;";
	String FETCH_CATEGORY_INFLUENCES_QUERY = "select bi.influence from app_category_influences bci inner join app_influences bi on bi.id = bci.influence_id where bci.category_id = ?;";
	String DELETE_FROM_CATEGORY_QUERY = "DELETE FROM app_category WHERE id = ?";
	String DELETE_CATEGORY_INFLUENCES_QUERY = "DELETE FROM app_category_influences WHERE category_id = ?";
	String ASSIGN_CATEGORIES_TO_COMPANY_QUERY = "INSERT INTO app_company_categories (id, company_id, category_id) VALUES(?,?,?)";
	String FETCH_COMPANY_CATEGORIES_QUERY = "select bc.category from app_company_details bcd inner join app_company_categories bcc on bcd.id = bcc.company_id inner join app_category bc on bc.id = bcc.category_id where bcd.id = ?;";
	String DELETE_COMPANY_CATEGORIES_QUERY = "DELETE FROM app_company_categories WHERE company_id = ?;";
	String VALIDATE_USER_QUERY = "SELECT 1 FROM app_user_details where email = ?";
	String VALIDATE_USER_ID_QUERY = "SELECT 1 FROM app_user_details where id = ?";
	String USER_STATUS_AND_USER_ID_QUERY = "SELECT is_active, id as user_id FROM app_user_details WHERE email = ?";
	String FETCH_ALL_USERS_REVIEWS_DETAILS_QUERY = "select bsa.id, bud.first_name, bud.email, bcd.name as company_name, bcd.city as location, bcd.id as company_id, bcd.country, bcd.logo, bsa.rating, bsa.description as review, bsa.created_on as reviewed_on from app_survey_answers bsa inner join app_user_details bud on bud.id = bsa.user_id inner join app_company_details bcd on bcd.id = bsa.company_id  order by to_timestamp(bsa.created_on, 'DD/MM/YY') desc;";
	String DELETE_FROM_SURVEY_ANSWERS_QUERY = "delete from app_survey_answers where id = ?;";
	String DELETE_SURVEY_ANSWER_INFLUENCE_QUERY = "delete from app_survey_answers_influences where survey_answers_id = ?;";
	String FETCH_COMPANY_CATEGORY_ID_QUERY = "select category_id from app_company_details where id = ?";
	String UPDATE_CATEGORY_QUERY = "update app_category set category = ?, description = ? where id = ? ";
	String FETCH_CATEGORY_INFLUENCES_IDS_QUERY = "select bi.id from app_category_influences bci inner join app_influences bi on bi.id = bci.influence_id where bci.category_id = ?;";
	String FETCH_COMPANY_CATEGORY_IDS_QUERY = "select bc.id from app_company_details bcd inner join app_company_categories bcc on bcd.id = bcc.company_id inner join app_category bc on bc.id = bcc.category_id where bcd.id = ?;";
	String FETCH_REVIEW_INFLUENCES_QUERY = "select bi.influence from app_survey_answers_influences bsai inner join app_influences bi on bi.id = bsai.influence_id where bsai.survey_answers_id = ?;";
	String FETCH_ALL_REWARDS_QUERY = "select * from app_rewards;";
	String TOGGLE_REWARD_STATUS_QUERY = "UPDATE app_rewards SET status = Case when status='Active' then 'Deactive' ELSE 'Active' END WHERE id = ?;";
	String DELETE_REWARD_QUERY = "delete from app_rewards where id = ?";
	String UPDATE_REWARD_QUERY = "UPDATE app_rewards SET name = ?, company = ?, reward_description = ?, type = ?, valid_from = ?, valid_till = ?, created_date = ?, reward_value = ?, no_of_rewards = ?, minimum_reviews = ?, status = ?, icon_url = ?, coupon_code = ?, offer_url = ? WHERE id = ?;";
	String VALIDATE_INDUSTRY_TAG_QUERY = "select * from app_industry_tag where industry_tag = ?";
	String ADD_INDUSTRY_TAG_QUERY = "insert into app_industry_tag (id, industry_tag) values(?,?)";
	String FETCH_INDUSTRY_TAG_ID_BY_INDUSTRY_TAG_QUERY = "select id from app_industry_tag where industry_tag = ?;";
	String ASSIGN_INDUSTRY_TAGS_TO_COMPANY_QUERY = "insert into app_company_industry_tag (id, company_id, industry_tag_id) values(?,?,?)";
	String DELETE_COMPANY_INDUSTRY_TAGS_QUERY = "delete from app_company_industry_tag where company_id = ?";
	String FETCH_RECENT_REVIEWED_COMPANIES_BY_USER_ID = "select *, bsa.created_on as reviewed_on from app_survey_answers bsa inner join app_company_details bcd on bcd.id = bsa.company_id where bsa.user_id = ? order by bsa.created_on limit ?;";
	String UPDATE_USER_COUNTRY_QUERY = "update app_user_details set country = ? where id = ?";
	String FETCH_INFLUENCES_BY_COMPANY_NAME_OR_COMPANY_ID = "SELECT bi.id, bi.influence, bi.influence_image FROM app_influences bi  INNER JOIN app_category_influences bci ON bi.id = bci.influence_id  INNER JOIN app_category bc ON bc.id = bci.category_id  INNER JOIN app_company_categories bcc ON bcc.category_id = bc.id  INNER JOIN app_company_details bcd ON bcd.id = bcc.company_id  WHERE bcd.id =  ? OR bcd.name = ?;";
	String FETCH_REWARD_IDS_AVAILABLE_FOR_USER = "SELECT r.id FROM app_rewards r WHERE  r.minimum_reviews <=(SELECT COUNT(1) FROM app_survey_answers WHERE user_id = ?)::text;";
	String FETCH_CURRENT_USER_REWARD_IDS_QUERY = "select r.reward_id from app_user_reward r where r.user_id = ?";
	String INSERT_INTO_APP_USER_REWARD_QUERY = "insert into app_user_reward (id, user_id, reward_id, is_claimed) values(?,?,?,?)";
	String REDUCE_AVAILABLE_REWARD_QUERY = "update app_rewards set no_of_rewards = no_of_rewards::int - 1 where id = ?;";
	String FETCH_REWARD_TYPE_BY_ID_QUERY = "SELECT type from app_rewards where id = ?";
	String FETCH_ALL_AUSTRALIAN_SUBURBS_QUERY = "SELECT * FROM postcodes_geo;";
}
